### Read all movies
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies


### Create a movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
    "title":"Start wars 4 ",
    "duration":200,
    "budget" : 900,
    "link" : "https://moodle.vinci.be/my/"
}


### Delete movie identified by 2
DELETE {{baseUrl}}/movies/2
